language: node_js
dist: trusty
sudo: false
node_js:
  - lts/argon
  - lts/boron
  - stable
script:
  - npm run coverage
install:
  - npm install --production
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
