name: Continuous Integration

on:
  push:
    paths-ignore:
      - '**.yml'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.md'
  schedule:
    - cron:  0 13 * * 1-5

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npx panva/npm-install-retry
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - lts/-2
          - lts/-1
          - lts/*
          - current
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx panva/npm-install-retry
      - run: npm run test
